x-condition-healthy: &healthy
  condition: service_healthy
x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5
services:
  app:
    build:
      context: .
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      database: *healthy
    volumes:
      - .:/app
    env_file:
      - .env
      - env.development
    command:
      - echo
      - "hello world"
  web:
    build:
      context: .
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      database: *healthy
    ports:
      - "3000:3000"
      - "9394:9394"
    volumes:
      - .:/app
    env_file:
      - .env
      - env.development
  database:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      !!merge <<: *healthcheck-defaults
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=database
  falma:
    build: ./fake_alma/.
    ports:
      - "4444:4567"
    volumes:
      - ./fake_alma/.:/app
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
volumes:
  database:
