name: Manual Deploy to Workshop
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true
jobs:
  build-unstable:
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@2012bb6a322ad02c45c01372de2f5e2e3d7329ac #v1.6.7
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit
  deploy-workshop:
    needs: build-unstable
    name: Deploy to workshop
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@2012bb6a322ad02c45c01372de2f5e2e3d7329ac #v1.6.7
    with:
      image: ${{ needs.build-unstable.outputs.image }}
      file: environments/account/workshop/checkout-history-web-image.txt
    secrets: inherit
