name: Run Tests
on: push
jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10
        env:
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: checkout_history_test
          MARIADB_ROOT_PASSWORD: password
        ports: ["3306:3306"]
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create .env file
        run: |
          sed 's/DATABASE_HOST=database/DATABASE_HOST=127.0.0.1/' env.development > env.actions
          cat env.example env.actions > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@d0a56edc74279820eabbe34477511327e710d0de #v2.4.0
      - name: Set up Ruby 4.0
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: 4.0
          bundler-cache: true
      - name: Verify MariaDB connection
        run: "while ! mysqladmin ping -h\"127.0.0.1\" -P\"3306\" --silent; do\n  sleep 1\ndone   \n"
      - name: Set up DB
        run: bundle exec rails db:schema:load RAILS_ENV=test
      - name: Run linter for Ruby
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rspec
